import "./globals.css";
import { Raleway, Merriweather_Sans } from "next/font/google";
import { Providers } from "./providers";
import clsx from "clsx";
import Nav from "@/components/Nav";

const raleway = Raleway({ subsets: ["latin"], variable: "--display-font" });
const merriweather = Merriweather_Sans({
  subsets: ["latin"],
  variable: "--body-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          "min-h-screen grid grid-cols-[auto_1fr]",
          raleway.className,
          raleway.variable,
          merriweather.className,
          merriweather.variable
        )}
      >
        <Providers>
          <Nav />
          <main className="bg-white dark:bg-slate-950 px-[5%] pt-10">
            <div className="max-w-[80rem] w-full mx-auto">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
